In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [21]:
import pandas as pd

fPath1 = r"\\ad.uws.edu.au\dfshare\HomesBLK$\90960046\My Documents\mycodelab\outputs-20260805T024105Z-1-001\outputs"

df = pd.read_parquet(fPath1 + r"\cohort_labels.parquet")
df.head(20)

,subject_id,index_hadm_id,index_admittime,index_dischtime,deathtime,admission_type,discharge_location,race,insurance,gender,...,n_eligible_admissions,type2_only_flag,index_los_days,primary_icd_dn_label,secondary_lab_proxy_label,strict_sensitivity_label,esrd_or_dialysis_flag,max_creatinine,max_bun,split
0,10000635,26134563,2136-06-19 14:24:00,2136-06-20 11:30:00,NaT,AMBULATORY OBSERVATION,None,BLACK/AFRICAN AMERICAN,Medicare,F,...,2,1,0.88,0,0,0,0,NaN,NaN,validation
1,10000980,29654838,2188-01-03 17:41:00,2188-01-05 17:30:00,NaT,EW EMER.,HOME HEALTH CARE,BLACK/AFRICAN AMERICAN,Medicare,F,...,7,1,1.99,0,1,0,0,1.4,31.0,test
2,10001176,23334588,2186-11-29 03:56:00,2186-12-02 15:00:00,NaT,EU OBSERVATION,None,WHITE,Medicare,F,...,1,0,3.46,0,0,0,0,0.9,19.0,train
3,10001843,21728396,2131-11-09 16:05:00,2131-11-11 11:23:00,NaT,OBSERVATION ADMIT,HOME HEALTH CARE,WHITE,Medicare,M,...,2,1,1.80,0,0,0,0,1.2,22.0,train
4,10001877,25679292,2149-05-21 15:53:00,2149-05-27 13:35:00,NaT,EW EMER.,SKILLED NURSING FACILITY,WHITE,Medicare,M,...,2,0,5.90,0,1,0,0,1.2,33.0,test
5,10002013,28603984,2156-06-28 15:53:00,2156-07-02 15:39:00,NaT,EW EMER.,HOME,WHITE,Medicaid,F,...,18,1,3.99,0,0,0,0,0.9,13.0,train
6,10002221,21008195,2200-09-29 17:28:00,2200-10-01 14:58:00,NaT,EW EMER.,HOME,WHITE,Medicare,F,...,6,1,1.90,0,0,0,0,NaN,NaN,train
7,10002443,21329021,2183-10-17 23:20:00,2183-10-20 18:47:00,NaT,EW EMER.,HOME,WHITE,Private,M,...,1,1,2.81,0,1,0,0,0.9,28.0,train
8,10002495,24982426,2141-05-22 20:17:00,2141-05-29 17:41:00,NaT,URGENT,SKILLED NURSING FACILITY,UNKNOWN,Medicare,M,...,1,1,6.89,0,1,0,0,1.6,45.0,train
9,10002976,27179825,2145-02-28 19:44:00,2145-03-05 16:45:00,NaT,EW EMER.,HOME,WHITE,Medicare,M,...,3,0,4.88,0,1,0,0,1.6,34.0,train
10,10003299,21743184,2173-05-12 12:29:00,2173-05-13 18:00:00,NaT,EW EMER.,HOME,BLACK/AFRICAN AMERICAN,Medicare,F,...,9,1,1.23,0,0,0,0,0.8,11.0,train
11,10004322,28755331,2131-01-23 21:30:00,2131-01-26 17:40:00,NaT,EU OBSERVATION,None,WHITE,Medicare,M,...,4,1,2.84,0,0,0,0,0.9,16.0,train
12,10005236,25656545,2177-11-29 11:30:00,2177-11-30 14:15:00,NaT,SURGICAL SAME DAY ADMISSION,HOME,UNKNOWN,Medicare,M,...,2,1,1.11,0,0,0,0,0.8,19.0,train
13,10005368,28912598,2130-05-30 07:15:00,2130-05-31 18:55:00,NaT,SURGICAL SAME DAY ADMISSION,HOME,WHITE,Private,M,...,2,0,1.49,0,0,0,0,0.8,9.0,train
14,10005593,26835370,2125-06-23 18:37:00,2125-07-03 20:14:00,NaT,OBSERVATION ADMIT,HOME HEALTH CARE,UNKNOWN,Medicaid,M,...,1,1,10.07,1,1,1,1,4.2,62.0,train
15,10005749,20010003,2140-09-23 17:59:00,2140-09-29 15:30:00,NaT,DIRECT EMER.,HOME HEALTH CARE,ASIAN - CHINESE,Medicaid,F,...,3,1,5.90,0,1,0,0,1.8,46.0,train
16,10005817,20626031,2132-12-12 01:43:00,2132-12-20 15:04:00,NaT,URGENT,HOME HEALTH CARE,WHITE,Medicare,M,...,2,1,8.56,0,0,0,0,1.1,25.0,validation
17,10006029,29107716,2169-08-20 16:50:00,2169-08-22 14:55:00,NaT,OBSERVATION ADMIT,HOME,WHITE,Medicare,M,...,4,1,1.92,1,1,1,0,1.3,18.0,train
18,10006457,27894366,2147-12-10 22:49:00,2147-12-17 13:30:00,NaT,EW EMER.,REHAB,UNKNOWN,Private,F,...,4,1,6.61,0,0,0,0,0.8,17.0,validation
19,10006508,20850343,2132-03-28 22:38:00,2132-04-02 15:00:00,NaT,OBSERVATION ADMIT,HOME HEALTH CARE,BLACK/AFRICAN AMERICAN,Medicare,F,...,10,1,4.68,0,1,0,0,1.6,47.0,train

In [23]:
df.shape

(46312, 21)

In [25]:
list(df.columns)

['subject_id',
 'index_hadm_id',
 'index_admittime',
 'index_dischtime',
 'deathtime',
 'admission_type',
 'discharge_location',
 'race',
 'insurance',
 'gender',
 'age_at_admission',
 'n_eligible_admissions',
 'type2_only_flag',
 'index_los_days',
 'primary_icd_dn_label',
 'secondary_lab_proxy_label',
 'strict_sensitivity_label',
 'esrd_or_dialysis_flag',
 'max_creatinine',
 'max_bun',
 'split']

In [13]:
import pandas as pd

fPath1 = r"\\ad.uws.edu.au\dfshare\HomesBLK$\90960046\My Documents\mycodelab\outputs-20260805T024105Z-1-001\outputs"

df1 = pd.read_parquet(fPath1 + r"\dx_sequences.parquet")
df1.head(20)

,subject_id,hadm_id,visit_number,age_at_visit,days_since_prev_visit,icd_code,icd_version,code_rank_within_visit,split
0,10000635,26134563,1,74,<NA>,42789,9,1,validation
1,10000635,26134563,1,74,<NA>,25000,9,2,validation
2,10000635,26134563,1,74,<NA>,4019,9,3,validation
3,10000980,29654838,1,75,<NA>,42833,9,1,test
4,10000980,29654838,1,75,<NA>,41189,9,2,test
5,10000980,29654838,1,75,<NA>,40390,9,3,test
6,10000980,29654838,1,75,<NA>,2724,9,4,test
7,10000980,29654838,1,75,<NA>,25000,9,5,test
8,10000980,29654838,1,75,<NA>,V5867,9,6,test
9,10000980,29654838,1,75,<NA>,V1254,9,7,test
10,10000980,29654838,1,75,<NA>,496,9,8,test
11,10000980,29654838,1,75,<NA>,4280,9,10,test
12,10000980,29654838,1,75,<NA>,V1581,9,11,test
13,10001176,23334588,1,64,<NA>,4829,9,1,train
14,10001176,23334588,1,64,<NA>,25000,9,2,train
15,10001176,23334588,1,64,<NA>,78060,9,3,train
16,10001176,23334588,1,64,<NA>,2761,9,4,train
17,10001176,23334588,1,64,<NA>,4019,9,5,train
18,10001176,23334588,1,64,<NA>,41401,9,6,train
19,10001176,23334588,1,64,<NA>,2724,9,7,train

In [16]:
print(df1.days_since_prev_visit.value_counts())

Series([], Name: count, dtype: Int64)

In [17]:
print(df1.split.value_counts())

split
train         415469
validation     90420
test           90238
Name: count, dtype: int64

In [19]:
df1.shape

(596127, 9)